language: java
jdk:
- openjdk8

script: "mvn deploy --settings settings.xml"
env:
  global:
  - secure: "aBG6R4sXjktck6L83FKswMyK3hxyExxzUzl9pMIJtPAL7R5sae2tquVOYGUcqYBGJLw5c6BvJcEP7Lm5sQgtS5DmGa+WplFne2kLe0rJUiIp3jKI/3M0Ei43mVWEnZCDlThrkqHlGOtznJbrLMl2fFThiUy0egSY/hfRM8GedaQReSYFFjOKTv5OiSH/XZl0iL2Hl1UmYHx0XNdaVHOZAHysS39cmetuNwQ+/ZEgzx4Md03Sm8HkvUCfzxt5WGxVFiZPmkFJAkafd5e3YiHXH8a1aqbQVzKGkL+vzxmIcL7bVy8k4WIizygvy2CM5e0duMJ7+aTBLU7T0EoT3oDNncFOsI7Zd4A0gZv99XU5SbYLykCU7AzUnIfXCGJlF78ik66IjPVYkxXpA9XREcuJNZnsQlmYcebzP4BEl37Ohs0Cs0eChww3hY1jVeY+wbsNpaMxBRSLaN84uMXmOnkCCvPGeU/wyIuXOpfOQJUrGT8MhWwTBVHGIdGOlBctACwae9oZ+resNg5ZSCptCWqdq64u62hC+g9DTFbQjd6czd5Ey/+ZZWxKzGgzHmK9abtF3rdajteKLStwiJhhAO0pkAqkW0zGIgW1ZOcToDSlQJ8MntUh7X5FKp97rGhon+oUIAJMTtTsgbiAJSQ4dI/jmpv9ugOq+kt/ip5aUCtyEeU="
  - secure: "vMuUlM+00ggFH3qXSmr7qFESFiVIsTgg50RfPBCE0wzRFNee0sYiFRSbnv+gRbVShUOQdu73zRn0IrdzvwJPcvWiMAUlzGgEs33dHvc+8Gd0JgiZaEPrghSWehXk3zglYN8FG6AXsfqnOpVUr+VrfpSPUxDCbtEHv4T3Uy1NWwQ647gAUjrPScrjDvChJwKUUT6qhXtUH17g2FDQdko/zTROzGDdi1dh+b8Z2/6o44XYKEiV+dUQDb1xtEf+i9b46GLaxNSfObh4JPHJm1qNAB/c9KPXw2uwtvt5N49c1ZlnJbr4TFnT2Fo6lW3euPuU7lq3Aj0N7+M+3yqjmDKZX4OGSBMmhZHZV6kaGija3qt5t2xWGONHdRgfbB5GisgUWgqhs96lr/vVtTyLlnUIEaYHZG5FjpLU4wh1X7aEwe4TSDPkBbuCe122JP6/EVRy0d7TKP6NvFpaXtNkIAcLX6Ocdt4EVRx6rU7bE7mScm4APYBl98+gICJGZhStkeQ2IwV1gTSdXaNHqO1lwK90o9OmDvt71eFZiGdW5nRWSsrh8iQN8pbWFjSVfEHp/lQy285Fkk1j4IKayTLDqkCjulxiwiMjUVz4BqnuNeTVXcPeQJx5g6lu6sUV5StDbrLCOV4nQRVTd5z336xQnw35XFGheLkhFRebci+3Zsvchlw="
deploy:
  provider: releases
  api_key: 
    secure: "ruzHebe4wUDA1Rz5xwsOM9Kb3BuA57wvRDHLi5zL8u8SsRQwgBVtzgi6i8fOHu2trbVjmYMs/1dCjI09qW684FX3CWFC8QqE4MD73phwej+EQKVINwCBnAVbQ/RudK5LmkjhAHNuYjMnk33qT3ASQDFBb3LUVBTXqwQC2B5Ll2t+o7Zcsd8na/4loRNtor16kl7Rxj3s9jCKsRQAWA5wfOPVEDSZC3JVEroIytDF8avP1icTd+0m5vWvMh+BQbUvnuiU9n//U6Vc70jydo9EmTGF6PIQ978mbAbEbhcjiAyH9xJ9z8GOWc31JZS0OQfTNOwGpAk0euE0VHvMZ0tV/jICCpAOX5k5LJkK02jXkWZ/sARpC5aCx5cu8nSSuMhlCgqqXMq1WjdQlG76JtO2VOW/z+A4tsW3rlJ+sanAZxFby2ukgJRVPPwxjUIMS8ZfqskKN6SEXo/3IQrcIWCEUUQ0QbGjmsUBvJqQzad6lP2Uylt9ICCczuVcng1exUk64sbS5fcDdrsjmxVEcmEQJ3wGxeHDK3Lhtk6NxdItqlsOnXgeAA75b+Gix/A9VUb2PIU7Xq/CIytV+iBxuYsbTyS3E4M/ZFgSOjB/xNZz+3nzfvXQDsvbRxCX2uSYBfChKmRDAwJjsFkKI4lG624bUzj1feMcuv7p/31mOdwREyI="
  file_glob: true
  file: 
    - "target/MapManager_v*.jar"
  skip_cleanup: true
  on:
    tags: true
